//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInformation
    {
        public int ItemInformationId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Remarks { get; set; }
        public int ItemCategoryId { get; set; }
        public int ItemTypeId { get; set; }
        public int UomId { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual Uom Uom { get; set; }
    }
}
