//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uom
    {
        public Uom()
        {
            this.ItemInformations = new HashSet<ItemInformation>();
        }
    
        public int UomId { get; set; }
        public string UomName { get; set; }
    
        public virtual ICollection<ItemInformation> ItemInformations { get; set; }
    }
}
