// <auto-generated />
namespace InventoryApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addinventorymodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addinventorymodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201412240547268_add-inventorymodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
